### ISSUE TITLE
Include info on financial aid programme on CfP page

### ISSUE THREAD

**Issue by keikoro** [djangocon/2016.djangocon.eu#10]
Opening an issue in connection with [this Twitter convo](https://twitter.com/kkvie/status/686346685358956544):

If you'll have a financial aid programme for this year's DjangoCon Europe again, it'd be great if you mentioned this on your CfP page (and possibly also the general website) ASAP. ASAP because the CfP closes soon, and this is relevant info for groups of potential speakers.

You wouldn't have to give details yet, just mention there'll be a fin aid programme, around which date you're planning to announce details on it and if you'll give preference to accepted speakers (or not). (:

If you're not planning to have a FA programme this time around, that'd be worth mentioning too _simply because_ there was one for the previous edition, so people might (wrongly, in this case) expect fin aid to be available again.

**Comment by keikoro** [comment]
Oups, and it'd also make sense to specify what financial aid means, e.g. money covering travel, or help with travel [+ amount if applicable] if that is indeed the case.

Just listing "financial aid" won't be of much help as fin aid differs from conf to conf and could mean anything from "free admission" (which already is a speakers perk anyway) to money for travel and/or accommodation, or a fixed or max. amount of € for any or only some of these things.

**Comment by bmispelon** [comment]
I started work on a branch: https://github.com/djangocon/2016.djangocon.eu/compare/scholarships?expand=1

Will review with the rest of the team and push today as soon as possible (and link from the CfP page).

If you see anything missing, please let us know. Thanks!

**Comment by bmispelon** [comment]
We just deployed our scholarship program page at https://2016.djangocon.eu/scholarships/.

Thanks again for your help on this and do let us know if you see something we can improve.
