### ISSUE TITLE
Setup https

### ISSUE THREAD

**Issue by bmispelon** [djangocon/2016.djangocon.eu#3]
https://twitter.com/fallenhitokiri/status/656565139513221120

I have no idea how to go about this. Any pointers?

**Comment by xavierdutreilh** [comment]
@bmispelon, aren't we supposed to buy a certificate for custom domains on Heroku? If I remember correctly, the **free** SSL certificate only applies to *.herokuapp.com.

Edit: found this entry in the documentation: https://devcenter.heroku.com/articles/ssl-endpoint

**Comment by xavierdutreilh** [comment]
@bmispelon, @jezdez resolved this issue a few weeks ago. So, I guess we can close this issue.
